flags: {}

extra-package-dbs: []

packages:
- '.'

extra-deps:
- QuickCheck-2.10.1 #This is only until a version of 'QuickCheck' that exports
                    #'UnicodeString' (2.10.1 is the first) is available in LTS.
# Remove once https://github.com/snoyberg/conduit/pull/347 (1.1.11) is available in LTS
- git: https://github.com/snoyberg/conduit.git
  commit: d90f4ddeec60022fa8070af58a8d1f6aa17c9f39
  subdirs:
  - resourcet

resolver: lts-9.14

nix:
    packages: [rocksdb,gmp]
